@startuml
class CategoriaBL {
    + _categoriaRepository : ICategoriaRepository <<get>> <<set>>
    + CategoriaBL(categoriaRepository:ICategoriaRepository)
    + Get() : IEnumerable<CategoriaDTO>
}
ICategoriaBL <|-- CategoriaBL
@enduml
