@startuml
class CategoriaController {
    + _categoriaBL : ICategoriaBL <<get>> <<set>>
    + CategoriaController(categoriaBL:ICategoriaBL)
    + Get() : ActionResult<IEnumerable<CategoriaDTO>>
}
ControllerBase <|-- CategoriaController
@enduml
