@startuml
!include .\\ConsoleApp1\Program.puml
!include .\\Games\Program.puml
!include .\\Games\Startup.puml
!include .\\Games\Controllers\CategoriaController.puml
!include .\\Games\Controllers\ComentarioController.puml
!include .\\Games\Controllers\JuegoController.puml
!include .\\Games\Controllers\LoginController.puml
!include .\\Games\Controllers\PlataformaController.puml
!include .\\Games\Controllers\UsuarioController.puml
!include .\\Games.BL\Contracts\ICategoriaBL.puml
!include .\\Games.BL\Contracts\IComentarioBL.puml
!include .\\Games.BL\Contracts\IJuegoBL.puml
!include .\\Games.BL\Contracts\IPlataformaBL.puml
!include .\\Games.BL\Contracts\IUsuarioBL.puml
!include .\\Games.BL\Implementations\CategoriaBL.puml
!include .\\Games.BL\Implementations\ComentarioBL.puml
!include .\\Games.BL\Implementations\JuegoBL.puml
!include .\\Games.BL\Implementations\PlataformaBL.puml
!include .\\Games.BL\Implementations\UsuarioBL.puml
!include .\\Games.Core\DTO\CategoriaDTO.puml
!include .\\Games.Core\DTO\ComentarioDTO.puml
!include .\\Games.Core\DTO\JuegoCategoriaDTO.puml
!include .\\Games.Core\DTO\JuegoDTO.puml
!include .\\Games.Core\DTO\PlataformaDTO.puml
!include .\\Games.Core\DTO\UsuarioDTO.puml
!include .\\Games.DAL\Entities\Category.puml
!include .\\Games.DAL\Entities\Comments.puml
!include .\\Games.DAL\Entities\db_gamesContext.puml
!include .\\Games.DAL\Entities\Games.puml
!include .\\Games.DAL\Entities\GamesCategory.puml
!include .\\Games.DAL\Entities\GamesPlatforms.puml
!include .\\Games.DAL\Entities\Platforms.puml
!include .\\Games.DAL\Entities\Users.puml
!include .\\Games.DAL\Repositories\Contracts\ICategoriaRepository.puml
!include .\\Games.DAL\Repositories\Contracts\IComentarioRepository.puml
!include .\\Games.DAL\Repositories\Contracts\IJuegoRepository.puml
!include .\\Games.DAL\Repositories\Contracts\IPlataformaRepository.puml
!include .\\Games.DAL\Repositories\Contracts\IUsuarioRepository.puml
!include .\\Games.DAL\Repositories\Implementations\CategoriaRepository.puml
!include .\\Games.DAL\Repositories\Implementations\ComentarioRepository.puml
!include .\\Games.DAL\Repositories\Implementations\JuegoRepository.puml
!include .\\Games.DAL\Repositories\Implementations\PlataformaRepository.puml
!include .\\Games.DAL\Repositories\Implementations\UsuarioRepository.puml
!include .\\ConsoleApp1\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\ConsoleApp1\obj\Debug\netcoreapp3.1\ConsoleApp1.AssemblyInfo.puml
!include .\\Games\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Games\obj\Debug\netcoreapp3.1\Games.AssemblyInfo.puml
!include .\\Games.BL\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Games.BL\obj\Debug\netcoreapp3.1\Games.BL.AssemblyInfo.puml
!include .\\Games.Core\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Games.Core\obj\Debug\netcoreapp3.1\Games.CORE.AssemblyInfo.puml
!include .\\Games.DAL\obj\Debug\netcoreapp3.1\.NETCoreApp,Version=v3.1.AssemblyAttributes.puml
!include .\\Games.DAL\obj\Debug\netcoreapp3.1\Games.DAL.AssemblyInfo.puml
@enduml
